/**
 * Generates docs/promoo-api-reference.json — all routes with correct payloads.
 * Run: npx tsx scripts/generate_api_reference.ts
 */

import * as fs from 'fs';
import * as path from 'path';

type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

interface ApiEndpoint {
  name: string;
  method: Method;
  path: string;
  requiresAuth: boolean;
  accountTypes?: string[];
  query?: Record<string, string | number | boolean | null>;
  pathParams?: Record<string, string>;
  body?: Record<string, unknown> | null;
  bodyType?: 'json' | 'multipart' | 'none';
  multipart?: Array<{ field: string; type: 'file' | 'text'; example?: string; required?: boolean }>;
  notes?: string;
}

interface ApiModule {
  module: string;
  endpoints: ApiEndpoint[];
}

const BASE_URL = 'http://localhost:3000/api/v1';

const modules: ApiModule[] = [
  {
    module: 'Auth',
    endpoints: [
      {
        name: 'Register Email',
        method: 'POST',
        path: '/auth/register/email',
        requiresAuth: false,
        bodyType: 'json',
        body: {
          email: 'user@example.com',
          password: 'password123',
          full_name: 'John Doe',
          account_type: 'user',
        },
        notes: 'account_type: company | influencer | service_provider | user',
      },
      {
        name: 'Register Phone',
        method: 'POST',
        path: '/auth/register/phone',
        requiresAuth: false,
        bodyType: 'json',
        body: {
          phone: '+963900000000',
          password: 'password123',
          full_name: 'John Doe',
          account_type: 'user',
        },
      },
      {
        name: 'Login Email',
        method: 'POST',
        path: '/auth/login/email',
        requiresAuth: false,
        bodyType: 'json',
        body: { email: 'user@example.com', password: 'password123' },
      },
      {
        name: 'Login Phone',
        method: 'POST',
        path: '/auth/login/phone',
        requiresAuth: false,
        bodyType: 'json',
        body: { phone: '+963900000000', password: 'password123' },
      },
      {
        name: 'OAuth Login',
        method: 'POST',
        path: '/auth/login/oauth',
        requiresAuth: false,
        bodyType: 'json',
        body: { provider: 'google', id_token: 'YOUR_ID_TOKEN', nonce: 'optional' },
        notes: 'provider: google | apple',
      },
      {
        name: 'Verify OTP',
        method: 'POST',
        path: '/auth/verify-otp',
        requiresAuth: false,
        bodyType: 'json',
        body: { email: 'user@example.com', token: '123456', type: 'signup' },
        notes: 'type: signup | magiclink | recovery | sms — email OR phone required',
      },
      {
        name: 'Refresh Token',
        method: 'POST',
        path: '/auth/refresh',
        requiresAuth: false,
        bodyType: 'json',
        body: { refresh_token: 'YOUR_REFRESH_TOKEN' },
      },
      {
        name: 'Forgot Password',
        method: 'POST',
        path: '/auth/forgot-password',
        requiresAuth: false,
        bodyType: 'json',
        body: { email: 'user@example.com' },
      },
      {
        name: 'Reset Password',
        method: 'POST',
        path: '/auth/reset-password',
        requiresAuth: true,
        bodyType: 'json',
        body: { password: 'newpassword123' },
      },
      { name: 'Logout', method: 'POST', path: '/auth/logout', requiresAuth: true, bodyType: 'none', body: null },
      { name: 'Delete Account', method: 'DELETE', path: '/auth/account', requiresAuth: true, bodyType: 'none', body: null },
    ],
  },
  {
    module: 'Profiles',
    endpoints: [
      { name: 'Get My Profile', method: 'GET', path: '/profiles/me', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Update My Profile',
        method: 'PUT',
        path: '/profiles/me',
        requiresAuth: true,
        bodyType: 'json',
        body: {
          full_name: 'Updated Name',
          username: 'myusername',
          bio: 'Short bio text',
          location: 'Dubai',
          website: 'https://example.com',
          category_id: '00000000-0000-0000-0000-000000000001',
          social_links: { instagram: 'https://instagram.com/user' },
        },
      },
      {
        name: 'Update Avatar',
        method: 'POST',
        path: '/profiles/me/avatar',
        requiresAuth: true,
        bodyType: 'json',
        body: { avatar_url: 'https://example.com/avatar.png' },
      },
      {
        name: 'Update Cover',
        method: 'POST',
        path: '/profiles/me/cover',
        requiresAuth: true,
        bodyType: 'json',
        body: { cover_url: 'https://example.com/cover.png' },
      },
      {
        name: 'Request Verification',
        method: 'POST',
        path: '/profiles/me/verify-request',
        requiresAuth: true,
        bodyType: 'json',
        body: { document_url: 'https://example.com/doc.pdf', notes: 'Please verify' },
      },
      {
        name: 'Get Profile by ID or Username',
        method: 'GET',
        path: '/profiles/:idOrUsername',
        requiresAuth: false,
        pathParams: { idOrUsername: 'uuid-or-username' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Profile Media',
        method: 'GET',
        path: '/profiles/:id/media',
        requiresAuth: false,
        pathParams: { id: 'profile-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Follows',
    endpoints: [
      {
        name: 'Follow Profile',
        method: 'POST',
        path: '/follows/:profileId',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Unfollow Profile',
        method: 'DELETE',
        path: '/follows/:profileId',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Check Follow Status',
        method: 'GET',
        path: '/follows/:profileId/status',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Followers',
        method: 'GET',
        path: '/follows/followers/:profileId',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Following',
        method: 'GET',
        path: '/follows/following/:profileId',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Offers',
    endpoints: [
      {
        name: 'Get All Offers',
        method: 'GET',
        path: '/offers',
        requiresAuth: false,
        query: { page: 1, limit: 20, category_id: null, min_price: null, max_price: null, search: null, location: null },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Offer by ID',
        method: 'GET',
        path: '/offers/:id',
        requiresAuth: false,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Offers by Profile',
        method: 'GET',
        path: '/offers/profile/:profileId',
        requiresAuth: false,
        pathParams: { profileId: 'profile-uuid' },
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Create Offer',
        method: 'POST',
        path: '/offers',
        requiresAuth: true,
        bodyType: 'json',
        body: {
          category_id: '00000000-0000-0000-0000-000000000001',
          title: 'Summer Sale',
          description: 'Detailed description of the offer (min 10 chars).',
          original_price: 100,
          offer_price: 50,
          discount_percentage: 50,
          media_urls: ['https://example.com/offer.jpg'],
          start_date: '2026-06-01T00:00:00.000Z',
          end_date: '2026-12-31T23:59:59.000Z',
          status: 'active',
          tags: ['sale', 'summer'],
        },
        notes: 'status: draft | active',
      },
      {
        name: 'Update Offer',
        method: 'PUT',
        path: '/offers/:id',
        requiresAuth: true,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'json',
        body: { title: 'Updated Sale', description: 'Updated offer description.' },
      },
      {
        name: 'Delete Offer',
        method: 'DELETE',
        path: '/offers/:id',
        requiresAuth: true,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Feature Offer',
        method: 'POST',
        path: '/offers/:id/feature',
        requiresAuth: true,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Ads',
    endpoints: [
      { name: 'Get Active Ads', method: 'GET', path: '/ads/active', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Record Impression',
        method: 'POST',
        path: '/ads/:id/impression',
        requiresAuth: false,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Record Click',
        method: 'POST',
        path: '/ads/:id/click',
        requiresAuth: false,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Create Ad',
        method: 'POST',
        path: '/ads',
        requiresAuth: true,
        accountTypes: ['company', 'influencer'],
        bodyType: 'json',
        body: {
          title: 'Summer Banner',
          description: 'Promotional banner campaign',
          media_url: 'https://example.com/ad-banner.jpg',
          ad_type: 'banner',
          target_url: 'https://example.com',
          budget: 100,
          start_date: '2026-06-01T00:00:00.000Z',
          end_date: '2026-12-31T23:59:59.000Z',
          phone: '+963900000000',
          whatsapp: '+963900000000',
          contact_email: 'ads@example.com',
          instagram_link: 'https://instagram.com/brand',
          city: 'Dubai',
          area: 'Marina',
          full_address: '123 Main St',
          location_map_url: 'https://maps.google.com/?q=Dubai',
          price: 99.99,
          currency: 'AED',
          service_type: 'delivery',
          payment_method: 'card',
          tags: ['promo', 'summer'],
        },
        notes: 'ad_type: banner | popup | featured',
      },
      {
        name: 'Update Ad',
        method: 'PUT',
        path: '/ads/:id',
        requiresAuth: true,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'json',
        body: { title: 'Updated Banner', budget: 150 },
      },
      {
        name: 'Toggle Ad',
        method: 'PATCH',
        path: '/ads/:id/toggle',
        requiresAuth: true,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Ad Stats',
        method: 'GET',
        path: '/ads/:id/stats',
        requiresAuth: true,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Profile Ads',
        method: 'GET',
        path: '/ads/profile/:profileId',
        requiresAuth: true,
        pathParams: { profileId: 'profile-uuid' },
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Services',
    endpoints: [
      { name: 'Get All Services', method: 'GET', path: '/services', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Get Service by ID',
        method: 'GET',
        path: '/services/:id',
        requiresAuth: false,
        pathParams: { id: 'service-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Create Service',
        method: 'POST',
        path: '/services',
        requiresAuth: true,
        accountTypes: ['service_provider', 'company'],
        bodyType: 'json',
        body: {
          category_id: '00000000-0000-0000-0000-000000000001',
          title: 'Professional Logo Design',
          description: 'High quality custom logo design for your brand identity.',
          price: 500,
          currency: 'AED',
          delivery_days: 3,
          media_urls: ['https://example.com/service.jpg'],
          tags: ['design', 'logo'],
        },
      },
      {
        name: 'Update Service',
        method: 'PUT',
        path: '/services/:id',
        requiresAuth: true,
        accountTypes: ['service_provider', 'company'],
        pathParams: { id: 'service-uuid' },
        bodyType: 'json',
        body: { price: 600, status: 'active' },
        notes: 'status: active | paused | deleted',
      },
      {
        name: 'Delete Service',
        method: 'DELETE',
        path: '/services/:id',
        requiresAuth: true,
        accountTypes: ['service_provider', 'company'],
        pathParams: { id: 'service-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Seats',
    endpoints: [
      {
        name: 'Get Available Seats',
        method: 'GET',
        path: '/seats',
        requiresAuth: false,
        query: { tier: 'gold' },
        bodyType: 'none',
        body: null,
        notes: 'tier optional: gold | silver | bronze',
      },
      { name: 'Get My Seats', method: 'GET', path: '/seats/me', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Book Seat',
        method: 'POST',
        path: '/seats/:id/book',
        requiresAuth: true,
        accountTypes: ['influencer'],
        pathParams: { id: 'seat-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Cancel Seat Booking',
        method: 'DELETE',
        path: '/seats/:id/cancel',
        requiresAuth: true,
        pathParams: { id: 'seat-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Stories',
    endpoints: [
      { name: 'Get Active Stories', method: 'GET', path: '/stories', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Get User Stories',
        method: 'GET',
        path: '/stories/user/:userId',
        requiresAuth: false,
        pathParams: { userId: 'user-uuid' },
        bodyType: 'none',
        body: null,
      },
      { name: 'Get My Stories', method: 'GET', path: '/stories/me', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Create Story',
        method: 'POST',
        path: '/stories',
        requiresAuth: true,
        bodyType: 'json',
        body: { media_url: 'https://example.com/story.mp4' },
      },
      {
        name: 'Delete Story',
        method: 'DELETE',
        path: '/stories/:id',
        requiresAuth: true,
        pathParams: { id: 'story-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Saved Items',
    endpoints: [
      { name: 'Get Saved Items', method: 'GET', path: '/saved', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Save Item',
        method: 'POST',
        path: '/saved',
        requiresAuth: true,
        bodyType: 'json',
        body: { item_id: '00000000-0000-0000-0000-000000000001', item_type: 'offer' },
        notes: 'item_type: offer | ad | profile',
      },
      {
        name: 'Unsave Item',
        method: 'DELETE',
        path: '/saved/:id',
        requiresAuth: true,
        pathParams: { id: 'saved-item-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Home',
    endpoints: [
      { name: 'Get Home Feed', method: 'GET', path: '/home', requiresAuth: false, bodyType: 'none', body: null },
    ],
  },
  {
    module: 'Subscriptions',
    endpoints: [
      { name: 'Get Plans', method: 'GET', path: '/subscriptions/plans', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Create Subscription',
        method: 'POST',
        path: '/subscriptions',
        requiresAuth: true,
        bodyType: 'json',
        body: { plan_id: '00000000-0000-0000-0000-000000000001', return_url: 'http://localhost:3000/dashboard/billing' },
      },
      { name: 'Get My Subscription', method: 'GET', path: '/subscriptions/me', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Manage Subscription',
        method: 'POST',
        path: '/subscriptions/manage',
        requiresAuth: true,
        bodyType: 'json',
        body: { return_url: 'http://localhost:3000/dashboard/billing' },
      },
    ],
  },
  {
    module: 'Chats',
    endpoints: [
      {
        name: 'Get Chat List',
        method: 'GET',
        path: '/chats',
        requiresAuth: true,
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Start Chat',
        method: 'POST',
        path: '/chats',
        requiresAuth: true,
        bodyType: 'json',
        body: { participant_id: '00000000-0000-0000-0000-000000000001' },
      },
      {
        name: 'Get Messages',
        method: 'GET',
        path: '/chats/:roomId/messages',
        requiresAuth: true,
        pathParams: { roomId: 'room-uuid' },
        query: { page: 1, limit: 50 },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Send Message',
        method: 'POST',
        path: '/chats/:roomId/messages',
        requiresAuth: true,
        pathParams: { roomId: 'room-uuid' },
        bodyType: 'json',
        body: { content: 'Hello!', type: 'text', media_url: 'https://example.com/file.jpg' },
        notes: 'type: text | image | video | file — content OR media_url required',
      },
      {
        name: 'Mark Messages Read',
        method: 'PATCH',
        path: '/chats/:roomId/read',
        requiresAuth: true,
        pathParams: { roomId: 'room-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Delete Chat',
        method: 'DELETE',
        path: '/chats/:roomId',
        requiresAuth: true,
        pathParams: { roomId: 'room-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Notifications',
    endpoints: [
      {
        name: 'Get Notifications',
        method: 'GET',
        path: '/notifications',
        requiresAuth: true,
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
      { name: 'Mark All as Read', method: 'PATCH', path: '/notifications/read-all', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Mark Notification as Read',
        method: 'PATCH',
        path: '/notifications/:id/read',
        requiresAuth: true,
        pathParams: { id: 'notification-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Delete Notification',
        method: 'DELETE',
        path: '/notifications/:id',
        requiresAuth: true,
        pathParams: { id: 'notification-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Register FCM Token',
        method: 'POST',
        path: '/notifications/token',
        requiresAuth: true,
        bodyType: 'json',
        body: { token: 'FCM_DEVICE_TOKEN', device_type: 'ios' },
        notes: 'device_type: ios | android | web',
      },
    ],
  },
  {
    module: 'Search & Categories',
    endpoints: [
      { name: 'Health Check', method: 'GET', path: '/health', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Global Search',
        method: 'GET',
        path: '/search',
        requiresAuth: false,
        query: { q: 'test', type: 'all', page: 1, limit: 20, categoryId: null, minPrice: null, maxPrice: null, location: null, accountType: null },
        bodyType: 'none',
        body: null,
        notes: 'type: profiles | offers | ads | all',
      },
      { name: 'Get Categories', method: 'GET', path: '/categories', requiresAuth: false, bodyType: 'none', body: null },
      {
        name: 'Get Category Content',
        method: 'GET',
        path: '/categories/:id/content',
        requiresAuth: false,
        pathParams: { id: 'category-uuid' },
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Featured',
    endpoints: [
      {
        name: 'Get Featured Listings',
        method: 'GET',
        path: '/featured',
        requiresAuth: false,
        query: { placement: 'home', page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
        notes: 'placement: home | search | category',
      },
      {
        name: 'Request Featured',
        method: 'POST',
        path: '/featured',
        requiresAuth: true,
        bodyType: 'json',
        body: { placement: 'home', duration_days: 7 },
      },
    ],
  },
  {
    module: 'Upload',
    endpoints: [
      {
        name: 'Upload Image',
        method: 'POST',
        path: '/upload/image',
        requiresAuth: true,
        bodyType: 'multipart',
        body: null,
        multipart: [
          { field: 'file', type: 'file', required: true },
          { field: 'related_to', type: 'text', example: 'offer', required: false },
          { field: 'related_id', type: 'text', example: 'uuid', required: false },
        ],
        notes: 'related_to: profile | offer | ad | chat',
      },
      {
        name: 'Upload Video',
        method: 'POST',
        path: '/upload/video',
        requiresAuth: true,
        bodyType: 'multipart',
        body: null,
        multipart: [
          { field: 'file', type: 'file', required: true },
          { field: 'related_to', type: 'text', example: 'offer', required: false },
          { field: 'related_id', type: 'text', example: 'uuid', required: false },
        ],
      },
      {
        name: 'Upload File',
        method: 'POST',
        path: '/upload/file',
        requiresAuth: true,
        bodyType: 'multipart',
        body: null,
        multipart: [
          { field: 'file', type: 'file', required: true },
          { field: 'related_to', type: 'text', example: 'chat', required: false },
          { field: 'related_id', type: 'text', example: 'uuid', required: false },
        ],
      },
      {
        name: 'Delete File',
        method: 'DELETE',
        path: '/upload/:fileId',
        requiresAuth: true,
        pathParams: { fileId: 'file-uuid' },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Payments',
    endpoints: [
      {
        name: 'Get Payment History',
        method: 'GET',
        path: '/payments/history',
        requiresAuth: true,
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
      { name: 'Create Customer Portal', method: 'POST', path: '/payments/portal', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Get Payment Details',
        method: 'GET',
        path: '/payments/:id',
        requiresAuth: true,
        pathParams: { id: 'payment-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Stripe Webhook',
        method: 'POST',
        path: '/webhooks/stripe',
        requiresAuth: false,
        bodyType: 'json',
        body: { type: 'checkout.session.completed', data: { object: {} } },
        notes: 'Registered in app.ts with raw body — requires Stripe-Signature header',
      },
    ],
  },
  {
    module: 'Reports',
    endpoints: [
      {
        name: 'Submit Report',
        method: 'POST',
        path: '/reports',
        requiresAuth: true,
        bodyType: 'json',
        body: {
          reported_id: '00000000-0000-0000-0000-000000000001',
          reported_type: 'profile',
          reason: 'spam content',
          details: 'Additional details (optional)',
        },
        notes: 'reported_type: profile | offer | ad | message',
      },
      {
        name: 'Get My Reports',
        method: 'GET',
        path: '/reports/me',
        requiresAuth: true,
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
    ],
  },
  {
    module: 'Admin',
    endpoints: [
      { name: 'Get Global Stats', method: 'GET', path: '/admin/stats', requiresAuth: true, bodyType: 'none', body: null, notes: 'Requires admin role' },
      {
        name: 'Create Category',
        method: 'POST',
        path: '/admin/categories',
        requiresAuth: true,
        bodyType: 'json',
        body: { name_en: 'Technology', name_ar: 'تقنية', icon_url: 'https://example.com/icon.png' },
      },
      {
        name: 'Update Category',
        method: 'PUT',
        path: '/admin/categories/:id',
        requiresAuth: true,
        pathParams: { id: 'category-uuid' },
        bodyType: 'json',
        body: { name_en: 'Tech & Innovation' },
      },
      {
        name: 'Delete Category',
        method: 'DELETE',
        path: '/admin/categories/:id',
        requiresAuth: true,
        pathParams: { id: 'category-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Update Offer Status',
        method: 'PATCH',
        path: '/admin/content/offers/:id/status',
        requiresAuth: true,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'json',
        body: { status: 'rejected' },
        notes: 'status: active | rejected | pending | expired | paused | completed',
      },
      {
        name: 'Delete Offer (Admin)',
        method: 'DELETE',
        path: '/admin/content/offers/:id',
        requiresAuth: true,
        pathParams: { id: 'offer-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Update Ad Status',
        method: 'PATCH',
        path: '/admin/content/ads/:id/status',
        requiresAuth: true,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'json',
        body: { status: 'active' },
      },
      {
        name: 'Delete Ad (Admin)',
        method: 'DELETE',
        path: '/admin/content/ads/:id',
        requiresAuth: true,
        pathParams: { id: 'ad-uuid' },
        bodyType: 'none',
        body: null,
      },
      { name: 'Get Admin Plans', method: 'GET', path: '/admin/plans', requiresAuth: true, bodyType: 'none', body: null },
      {
        name: 'Create Plan',
        method: 'POST',
        path: '/admin/plans',
        requiresAuth: true,
        bodyType: 'json',
        body: {
          stripe_price_id: 'price_1234567890',
          name_en: 'Pro Plan',
          name_ar: 'الخطة الاحترافية',
          description_en: 'Full access',
          description_ar: 'وصول كامل',
          price: 9.99,
          currency: 'usd',
          interval: 'month',
          features_en: ['Unlimited offers'],
          features_ar: ['عروض غير محدودة'],
          is_active: true,
        },
        notes: 'interval: month | year',
      },
      {
        name: 'Update Plan',
        method: 'PUT',
        path: '/admin/plans/:id',
        requiresAuth: true,
        pathParams: { id: 'plan-uuid' },
        bodyType: 'json',
        body: { is_active: false },
      },
      {
        name: 'Delete Plan',
        method: 'DELETE',
        path: '/admin/plans/:id',
        requiresAuth: true,
        pathParams: { id: 'plan-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get Users',
        method: 'GET',
        path: '/admin/users',
        requiresAuth: true,
        query: { page: 1, limit: 20, search: null, accountType: null, isVerified: null, isActive: null },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get User Details',
        method: 'GET',
        path: '/admin/users/:id',
        requiresAuth: true,
        pathParams: { id: 'user-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Toggle User Ban',
        method: 'PATCH',
        path: '/admin/users/:id/ban',
        requiresAuth: true,
        pathParams: { id: 'user-uuid' },
        bodyType: 'json',
        body: { isActive: false },
      },
      {
        name: 'Toggle User Verify',
        method: 'PATCH',
        path: '/admin/users/:id/verify',
        requiresAuth: true,
        pathParams: { id: 'user-uuid' },
        bodyType: 'json',
        body: { isVerified: true },
      },
      {
        name: 'Delete User',
        method: 'DELETE',
        path: '/admin/users/:id',
        requiresAuth: true,
        pathParams: { id: 'user-uuid' },
        bodyType: 'none',
        body: null,
      },
      {
        name: 'Get All Reports',
        method: 'GET',
        path: '/admin/reports',
        requiresAuth: true,
        query: { page: 1, limit: 20, status: 'pending', type: null },
        bodyType: 'none',
        body: null,
        notes: 'status: pending | reviewed | resolved | dismissed',
      },
      {
        name: 'Update Report Status',
        method: 'PATCH',
        path: '/admin/reports/:id/status',
        requiresAuth: true,
        pathParams: { id: 'report-uuid' },
        bodyType: 'json',
        body: { status: 'resolved', admin_note: 'Issue addressed' },
      },
      {
        name: 'Get Admin Payments',
        method: 'GET',
        path: '/admin/payments',
        requiresAuth: true,
        query: { page: 1, limit: 20 },
        bodyType: 'none',
        body: null,
      },
    ],
  },
];

function enrichEndpoint(ep: ApiEndpoint) {
  return {
    ...ep,
    fullUrl: `${BASE_URL}${ep.path}`,
    headers: ep.requiresAuth
      ? { Authorization: 'Bearer <access_token>', ...(ep.bodyType === 'json' ? { 'Content-Type': 'application/json' } : {}) }
      : ep.bodyType === 'json'
        ? { 'Content-Type': 'application/json' }
        : {},
  };
}

const totalEndpoints = modules.reduce((n, m) => n + m.endpoints.length, 0);

const reference = {
  info: {
    name: 'Promoo API Reference',
    description: 'All API routes with correct request payloads — generated from src/routes and validators',
    version: 'v1',
    baseUrl: BASE_URL,
    generatedAt: new Date().toISOString(),
    totalEndpoints,
    auth: {
      type: 'Bearer Token',
      header: 'Authorization: Bearer <access_token>',
      howToGetToken: 'POST /auth/login/email → data.session.access_token',
    },
    responseFormat: {
      success: true,
      data: '...',
      message: 'string',
      meta: 'optional pagination { page, limit, total, totalPages }',
    },
  },
  modules: modules.map((m) => ({
    module: m.module,
    count: m.endpoints.length,
    endpoints: m.endpoints.map(enrichEndpoint),
  })),
  flatEndpoints: modules.flatMap((m) =>
    m.endpoints.map((ep) => ({ module: m.module, ...enrichEndpoint(ep) }))
  ),
};

const outDir = path.join(__dirname, '..', 'docs');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const outPath = path.join(outDir, 'promoo-api-reference.json');
fs.writeFileSync(outPath, JSON.stringify(reference, null, 2), 'utf-8');

console.log(`✅ Generated ${outPath}`);
console.log(`   Modules: ${modules.length}`);
console.log(`   Endpoints: ${totalEndpoints}`);
